// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeqnqAonrUnQ7dNR-tEiXVdnYLGXrtYD4',
    appId: '1:687075832094:web:24801c42a8ebdd748e190f',
    messagingSenderId: '687075832094',
    projectId: 'moodylune',
    authDomain: 'moodylune.firebaseapp.com',
    storageBucket: 'moodylune.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOwreYK5IZw_sQyclZ6552fNxNYahUajc',
    appId: '1:687075832094:android:06c79f60045a61bb8e190f',
    messagingSenderId: '687075832094',
    projectId: 'moodylune',
    storageBucket: 'moodylune.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD25cm4FKud2luQX7JKwD5s0j5xXRqHcXQ',
    appId: '1:687075832094:ios:8f0b22a473dc7af18e190f',
    messagingSenderId: '687075832094',
    projectId: 'moodylune',
    storageBucket: 'moodylune.firebasestorage.app',
    iosBundleId: 'com.example.moodylune',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD25cm4FKud2luQX7JKwD5s0j5xXRqHcXQ',
    appId: '1:687075832094:ios:8f0b22a473dc7af18e190f',
    messagingSenderId: '687075832094',
    projectId: 'moodylune',
    storageBucket: 'moodylune.firebasestorage.app',
    iosBundleId: 'com.example.moodylune',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeqnqAonrUnQ7dNR-tEiXVdnYLGXrtYD4',
    appId: '1:687075832094:web:608d77d5e2dd66d78e190f',
    messagingSenderId: '687075832094',
    projectId: 'moodylune',
    authDomain: 'moodylune.firebaseapp.com',
    storageBucket: 'moodylune.firebasestorage.app',
  );
}
