name: Flutter Build Release APK

on:
  push:
    branches:
      - main
  workflow_dispatch:   # allows manual trigger in GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.6" # replace with your flutter version

      # Run flutter pub get
      - name: Install dependencies
        run: flutter pub get

      # Build APK
      - name: Build release APK
        run: flutter build apk --release

      # Upload the APK as artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
